dlp:
  serviceRegistry:
    username: serviceregistry
    password: 'dlp123sr'
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${dlp.serviceRegistry.username}:${dlp.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost