server:
  port: 8087
  servlet:
    context-path: '/dlp-authuser/'
spring:
  application:
    name: dlp-authuser-service
  datasource:
    url: jdbc:mysql://config-repo:3306/authuser
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      id.new_generator_mappings: true
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://xlcwbsal:8_vWUtzx_a3Z8AoXfLcI_LBvVwaLFh8Z@moose.rmq.cloudamqp.com/xlcwbsal
logging:
  level:
    com.dlp: INFO
    root: INFO
    prg.springframework.web: INFO
dlp:
  api:
    url:
      course: 'http://dlp-course-service/dlp-course'
  broker:
    exchange:
      userEvent: dlp.user.event

authuser:
  refreshscope:
    name: Michelli Nogueira

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

resilience4j:
  circuitbreaker:
    instances:
      circuitBreakInstance:
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 2
        wait-duration-in-open-state:
          30s
        failure-rate-threshold: 80
  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s
